#!/bin/bash

CYAN='\033[0;36m'
RED_COLOR='\033[0;31m'
RESET_COLOR='\033[0m'
ORANGE_COLOR='\033[0;33m'

INFO_FLAG="[${CYAN}INFO${RESET_COLOR}]"
ERROR_FLAG="[${RED_COLOR}ERROR${RESET_COLOR}]"
WARN_FLAG="[${ORANGE_COLOR}WARN${RESET_COLOR}]"
