on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{secrets.PRIVATE_GH_TOKEN}}
          release-type: node
