name: CI - Tests

on:
  push:
    branches: 
      - "!main"

jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [12.x, 14.x, 16.x, 18.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: ${{matrix.node}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test

