name: CI - Tests

on:
  push:
    paths:
      - lib/**
    branches: 
      - "**"

jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [18.x, 20.x, 21.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: ${{matrix.node}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test

      - uses: coverallsapp/github-action@v2
        name: Coveralls
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

